#!/usr/bin/env python

from glob import glob
import sys

var_path = sys.argv[1]
case_files = sorted(glob(f"{var_path}*var_list.txt"))

with open(case_files[0], "r") as file:
    readline=file.read().splitlines()

with open(case_files[1], "r") as file:
    readline2=file.read().splitlines()

matched = sorted(list(set(readline) & set(readline2)))

with open(f"{var_path}case_matched_var_list.txt",'w') as f:
    for i in matched:
        f.write(f"{i.replace(',','')}\n")